# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "MINT Lab"
title:              "MINT Lab at Vanderbilt University"
description:        "this is a page for MINT Lab, we are the Machine Intelligence and Neural Technologies Lab at Vanderbilt Unviersity, Nashville, TN."


# URL
url:                https://mint-vu.github.io
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "people"
    href:           "/people"
  - name:           "Projects"
    href:           "/projects"
  - name:           "publications"
    href:           "/publication"
  - name:           "resources"
    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
